{"name": "ansible", "cve_id": "CVE-2019-14846", "publish_date": "2019-10-08T19:15Z", "cwe_id": "CWE-532", "owner": "ansible", "affected_versions": [{"version_value": "2.8.5", "operator": "<="}], "references": ["http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html", "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html", "https://access.redhat.com/errata/RHSA-2019:3201", "https://access.redhat.com/errata/RHSA-2019:3202", "https://access.redhat.com/errata/RHSA-2019:3203", "https://access.redhat.com/errata/RHSA-2019:3207", "https://access.redhat.com/errata/RHSA-2020:0756", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14846", "https://github.com/ansible/ansible/pull/63366", "https://lists.debian.org/debian-lts-announce/2020/05/msg00005.html"], "description": "Ansible, all ansible_engine-2.x versions and ansible_engine-3.x up to ansible_engine-3.5, was logging at the DEBUG level which lead to a disclosure of credentials if a plugin used a library that logged credentials at the DEBUG level. This flaw does not affect Ansible modules, as those are executed in a separate process.", "latest_version": "2.10.0", "language": "python", "license": "GPL-3.0-or-later", "repository_summary": "Radically simple IT automation", "repo_url": "https://ansible.com/", "impact": {"cvss2_score": 2.1, "cvss2_severity": "LOW", "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "av": "LOCAL", "ac": "LOW", "pr": "LOW", "c": "HIGH", "i": "HIGH", "a": "HIGH", "impact_score": 5.9, "exploitability_score": 1.8, "cvss3_score": 7.8, "cvss3_severity": "HIGH", "ui": "NONE", "s": "UNCHANGED"}, "ochrona_severity_score": 7.8}