{
    "name": "django",
    "cve_id": "CVE-2020-24584",
    "publish_date": "2020-09-01T13:15Z",
    "cwe_id": "CWE-276",
    "owner": "Django Software Foundation",
    "affected_versions": [
        {"version_value": "2.2", "operator": "="},
        {"version_value": "2.2.1", "operator": "="},
        {"version_value": "2.2.2", "operator": "="},
        {"version_value": "2.2.3", "operator": "="},
        {"version_value": "2.2.4", "operator": "="},
        {"version_value": "2.2.5", "operator": "="},
        {"version_value": "2.2.6", "operator": "="},
        {"version_value": "2.2.7", "operator": "="},
        {"version_value": "2.2.8", "operator": "="},
        {"version_value": "2.2.9", "operator": "="},
        {"version_value": "2.2.10", "operator": "="},
        {"version_value": "2.2.11", "operator": "="},
        {"version_value": "2.2.12", "operator": "="},
        {"version_value": "2.2.13", "operator": "="},
        {"version_value": "2.2.14", "operator": "="},
        {"version_value": "2.2.15", "operator": "="},
        {"version_value": "3.0", "operator": "="},
        {"version_value": "3.0.1", "operator": "="},
        {"version_value": "3.0.2", "operator": "="},
        {"version_value": "3.0.3", "operator": "="},
        {"version_value": "3.0.4", "operator": "="},
        {"version_value": "3.0.5", "operator": "="},
        {"version_value": "3.0.6", "operator": "="},
        {"version_value": "3.0.7", "operator": "="},
        {"version_value": "3.0.8", "operator": "="},
        {"version_value": "3.0.9", "operator": "="},
        {"version_value": "3.1", "operator": "="}
    ],
    "references": [
        "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
        "https://usn.ubuntu.com/4479-1/",
        "https://www.oracle.com/security-alerts/cpujan2021.html",
        "https://security.netapp.com/advisory/ntap-20200918-0004/",
        "https://docs.djangoproject.com/en/dev/releases/security/",
        "https://nvd.nist.gov/vuln/detail/CVE-2020-24584",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/",
        "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
        "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
        "https://github.com/advisories/GHSA-fr28-569j-53c4",
        "https://www.openwall.com/lists/oss-security/2020/09/01/2",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/"
    ],
    "description": "From NVD:\nAn issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.\nFrom Github:\nAn issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.",
    "latest_version": "3.1.3",
    "language": "python",
    "license": "BSD-3-Clause",
    "repository_summary": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.",
    "repo_url": "https://www.djangoproject.com/",
    "impact": {
        "cvss2_score": 5.0,
        "cvss2_severity": "MEDIUM",
        "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "av": "NETWORK",
        "ac": "LOW",
        "pr": "NONE",
        "c": "HIGH",
        "i": "NONE",
        "a": "NONE",
        "impact_score": 3.6,
        "exploitability_score": 3.9,
        "cvss3_score": 7.5,
        "cvss3_severity": "HIGH",
        "ui": "NONE",
        "s": "UNCHANGED"
    },
    "ochrona_severity_score": 7.5
}