{
    "name": "Django",
    "cve_id": "CVE-2021-45116",
    "publish_date": "2022-01-05T00:15Z",
    "cwe_id": "CWE-668",
    "owner": "Django Software Foundation",
    "affected_versions": [
        {
            "operator": "=",
            "version_value": "2.2"
        },
        {
            "operator": "=",
            "version_value": "2.2.1"
        },
        {
            "operator": "=",
            "version_value": "2.2.2"
        },
        {
            "operator": "=",
            "version_value": "2.2.3"
        },
        {
            "operator": "=",
            "version_value": "2.2.4"
        },
        {
            "operator": "=",
            "version_value": "2.2.5"
        },
        {
            "operator": "=",
            "version_value": "2.2.6"
        },
        {
            "operator": "=",
            "version_value": "2.2.7"
        },
        {
            "operator": "=",
            "version_value": "2.2.8"
        },
        {
            "operator": "=",
            "version_value": "2.2.9"
        },
        {
            "operator": "=",
            "version_value": "2.2.10"
        },
        {
            "operator": "=",
            "version_value": "2.2.11"
        },
        {
            "operator": "=",
            "version_value": "2.2.12"
        },
        {
            "operator": "=",
            "version_value": "2.2.13"
        },
        {
            "operator": "=",
            "version_value": "2.2.14"
        },
        {
            "operator": "=",
            "version_value": "2.2.15"
        },
        {
            "operator": "=",
            "version_value": "2.2.16"
        },
        {
            "operator": "=",
            "version_value": "2.2.17"
        },
        {
            "operator": "=",
            "version_value": "2.2.18"
        },
        {
            "operator": "=",
            "version_value": "2.2.19"
        },
        {
            "operator": "=",
            "version_value": "2.2.20"
        },
        {
            "operator": "=",
            "version_value": "2.2.21"
        },
        {
            "operator": "=",
            "version_value": "2.2.22"
        },
        {
            "operator": "=",
            "version_value": "2.2.23"
        },
        {
            "operator": "=",
            "version_value": "2.2.24"
        },
        {
            "operator": "=",
            "version_value": "2.2.25"
        },
        {
            "operator": "=",
            "version_value": "3.2"
        },
        {
            "operator": "=",
            "version_value": "3.2.1"
        },
        {
            "operator": "=",
            "version_value": "3.2.2"
        },
        {
            "operator": "=",
            "version_value": "3.2.3"
        },
        {
            "operator": "=",
            "version_value": "3.2.4"
        },
        {
            "operator": "=",
            "version_value": "3.2.5"
        },
        {
            "operator": "=",
            "version_value": "3.2.6"
        },
        {
            "operator": "=",
            "version_value": "3.2.7"
        },
        {
            "operator": "=",
            "version_value": "3.2.8"
        },
        {
            "operator": "=",
            "version_value": "3.2.9"
        },
        {
            "operator": "=",
            "version_value": "3.2.10"
        },
        {
            "operator": "=",
            "version_value": "4.0"
        }
    ],
    "references": [
        "https://nvd.nist.gov/vuln/detail/CVE-2021-45116",
        "https://groups.google.com/forum/#!forum/django-announce",
        "https://github.com/advisories/GHSA-8c5j-9r9f-c6w8",
        "https://www.djangoproject.com/weblog/2022/jan/04/security-releases/",
        "https://docs.djangoproject.com/en/4.0/releases/security/"
    ],
    "description": "From NVD:\nAn issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key.\nFrom Github:\nAn issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key.",
    "latest_version": "4.0.1",
    "language": "python",
    "license": "BSD-3-Clause",
    "repository_summary": "A high-level Python Web framework that encourages rapid development and clean, pragmatic design.",
    "repo_url": "https://github.com/django/django",
    "impact": {
        "cvss2_score": 5.0,
        "cvss2_severity": "MEDIUM",
        "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "av": "NETWORK",
        "ac": "LOW",
        "pr": "NONE",
        "c": "HIGH",
        "i": "NONE",
        "a": "NONE",
        "impact_score": 3.6,
        "exploitability_score": 3.9,
        "cvss3_score": 7.5,
        "cvss3_severity": "HIGH",
        "ui": "NONE",
        "s": "UNCHANGED"
    },
    "ochrona_severity_score": 7.5
}