{
    "name": "opencv-contrib-python",
    "cve_id": "CVE-2016-1517",
    "publish_date": "2017-04-10T03:59Z",
    "cwe_id": "CWE-20",
    "owner": "Olli-Pekka Heinisuo",
    "affected_versions": [
        {
            "version_value": "3.3.0.10",
            "operator": "<="
        }
    ],
    "references": [
        "https://arxiv.org/pdf/1701.04739.pdf",
        "https://github.com/opencv/opencv/issues/5956",
        "https://github.com/advisories/GHSA-fffj-9qwg-qmh5",
        "https://nvd.nist.gov/vuln/detail/CVE-2016-1517"
    ],
    "description": "From NVD:\nOpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.\nFrom Github:\nOpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV 3.3.1.11).",
    "latest_version": "4.5.3.56",
    "language": "python",
    "license": "MIT",
    "repository_summary": "Wrapper package for OpenCV python bindings.",
    "repo_url": "https://github.com/skvark/opencv-python",
    "impact": {
        "cvss2_score": 4.3,
        "cvss2_severity": "MEDIUM",
        "vector_string": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
        "av": "LOCAL",
        "ac": "LOW",
        "pr": "NONE",
        "c": "NONE",
        "i": "NONE",
        "a": "HIGH",
        "impact_score": 3.6,
        "exploitability_score": 1.8,
        "cvss3_score": 5.5,
        "cvss3_severity": "MEDIUM",
        "ui": "REQUIRED",
        "s": "UNCHANGED"
    },
    "ochrona_severity_score": 5.5
}