{"name": "pyyaml", "cve_id": "CVE-2020-1747", "publish_date": "2020-03-24T15:15Z", "cwe_id": "CWE-20", "owner": "Kirill Simonov", "affected_versions": [{"version_value": "5.3.0", "operator": "<="}], "references": ["http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html", "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747", "https://github.com/yaml/pyyaml/pull/386", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/"], "description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.", "latest_version": "5.3.1", "language": "python", "license": "MIT", "repository_summary": "YAML parser and emitter for Python", "repo_url": "https://github.com/yaml/pyyaml", "impact": {"cvss2_score": 10.0, "cvss2_severity": "HIGH", "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "av": "NETWORK", "ac": "LOW", "pr": "NONE", "c": "HIGH", "i": "HIGH", "a": "HIGH", "impact_score": 5.9, "exploitability_score": 3.9, "cvss3_score": 9.8, "cvss3_severity": "CRITICAL", "ui": "NONE", "s": "UNCHANGED"}, "ochrona_severity_score": 9.8}