{"name": "roundup", "cve_id": "CVE-2019-10904", "publish_date": "2019-04-06T20:29Z", "cwe_id": "CWE-79", "owner": "roundup-tracker", "affected_versions": [{"version_value": "1.6", "operator": "<="}], "references": ["http://www.openwall.com/lists/oss-security/2019/04/07/1", "https://bugs.python.org/issue36391", "https://github.com/python/bugs.python.org/issues/34", "https://lists.debian.org/debian-lts-announce/2019/04/msg00009.html", "https://www.openwall.com/lists/oss-security/2019/04/05/1"], "description": "Roundup 1.6 allows XSS via the URI because frontends/roundup.cgi and roundup/cgi/wsgi_handler.py mishandle 404 errors.", "latest_version": "1.6.1", "language": "python", "license": "MIT", "repository_summary": "A simple-to-use and -install issue-tracking system with command-line, web and e-mail interfaces. Highly customisable.", "repo_url": "http://www.roundup-tracker.org", "impact": {"cvss2_score": 4.3, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N", "av": "NETWORK", "ac": "LOW", "pr": "NONE", "c": "LOW", "i": "LOW", "a": "NONE", "impact_score": 2.7, "exploitability_score": 2.8, "cvss3_score": 6.1, "cvss3_severity": "MEDIUM", "ui": "REQUIRED", "s": "CHANGED"}, "ochrona_severity_score": 6.1}