{"name": "tensorflow", "cve_id": "GHSA-43q8-3fv7-pr5x", "publish_date": "2022-02-09T23:37:55Z", "cwe_id": null, "owner": "Google Inc.", "affected_versions": [{"version_value": "2.8.0","operator": "<"}], "references": ["https://github.com/tensorflow/tensorflow/security/advisories/GHSA-43q8-3fv7-pr5x", "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-pgcq-h79j-2f69", "https://github.com/tensorflow/tensorflow/pull/53695", "https://github.com/tensorflow/tensorflow/commit/61bf91e768173b001d56923600b40d9a95a04ad5", "https://github.com/advisories/GHSA-43q8-3fv7-pr5x"], "description": "### Impact\nThe implementation of [`tf.sparse.split`](https://github.com/tensorflow/tensorflow/blob/5100e359aef5c8021f2e71c7b986420b85ce7b3d/tensorflow/core/kernels/sparse_split_op.cc#L26-L102) does not fully validate the input arguments. Hence, a malicious user can trigger a denial of service via a segfault or a heap OOB read:\n\n```python\nimport tensorflow as tf\ndata = tf.random.uniform([1, 32, 32], dtype=tf.float32)\naxis = [1, 2]\nx = tf.sparse.from_dense(data)\nresult = tf.sparse.split(x,3, axis=axis)\n```\nThe code assumes `axis` is a scalar. This is another instance of [TFSA-2021-190](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2021-190.md) (CVE-2021-41206).\n\n### Patches\nWe have patched the issue in GitHub commit [61bf91e768173b001d56923600b40d9a95a04ad5](https://github.com/tensorflow/tensorflow/commit/61bf91e768173b001d56923600b40d9a95a04ad5) (merging [#53695](https://github.com/tensorflow/tensorflow/pull/53695)).\n\nThe fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported externally via a [GitHub issue](https://github.com/tensorflow/tensorflow/issues/53660).", "latest_version": "2.8.0", "language": "python", "license": "Apache-2.0", "repository_summary": "TensorFlow is an open source machine learning framework for everyone.", "repo_url": "https://github.com/tensorflow/tensorflow", "impact": {"cvss3_score": null, "cvss3_severity": null, "av": null, "ac": null, "pr": null, "ui": null, "s": null, "c": null, "i": null, "a": null, "impact_score": null, "exploitability_score": null}, "ochrona_severity_score": 7}