{"name": "tuf", "cve_id": "CVE-2020-15163", "publish_date": "2020-09-09T18:15Z", "cwe_id": "CWE-863", "owner": "https://www.updateframework.com", "affected_versions": [{"version_value": "0.12", "operator": "<"}], "references": ["https://github.com/theupdateframework/tuf/releases/tag/v0.12.0", "https://github.com/advisories/GHSA-f8mr-jv2c-v8mg", "https://pypi.org/project/tuf", "https://nvd.nist.gov/vuln/detail/CVE-2020-15163", "https://github.com/theupdateframework/tuf/commit/3d342e648fbacdf43a13d7ba8886aaaf07334af7", "https://github.com/theupdateframework/tuf/security/advisories/GHSA-f8mr-jv2c-v8mg", "https://github.com/theupdateframework/tuf/pull/885"], "description": "From NVD:\nPython TUF (The Update Framework) reference implementation before version 0.12 it will incorrectly trust a previously downloaded root metadata file which failed verification at download time. This allows an attacker who is able to serve multiple new versions of root metadata (i.e. by a person-in-the-middle attack) culminating in a version which has not been correctly signed to control the trust chain for future updates. This is fixed in version 0.12 and newer.\nFrom Github:\n### Impact\nThe Python TUF reference implementation `tuf<0.12` will incorrectly trust a previously downloaded root metadata file which failed verification at download time. This allows an attacker who is able to serve multiple new versions of root metadata (i.e. by a man-in-the-middle attack) culminating in a version which has not been correctly signed to control the trust chain for future updates.\n\nWhile investigating the reported vulnerability, we discovered that the detailed client workflow was not fully implemented. Specifically, for step 1.3 the newly downloaded root metadata was not being verified with a threshold of keys specified in the new root metadata file.\nThis missing step of the client workflow has been implemented in [PR #1101](https://github.com/theupdateframework/tuf/pull/1101), which is included in [v0.14.0](https://github.com/theupdateframework/tuf/releases/tag/v0.14.0) of tuf.\n\n### Patches\nA [fix](https://github.com/theupdateframework/tuf/pull/885), is available in version [0.12](https://github.com/theupdateframework/tuf/releases/tag/v0.12.0) and newer.\n\n### Workarounds\nNo workarounds are known for this issue.\n\n### References\n* Pull request resolving the invalid root becoming trusted issue [PR 885](https://github.com/theupdateframework/tuf/pull/885)\n* Pull request implementing self verification of newly downloaded root metadata [PR 1101](https://github.com/theupdateframework/tuf/pull/1101)", "latest_version": "0.15.0", "language": "python", "license": "Apache-2.0", "repository_summary": "A secure updater framework for Python", "repo_url": "https://github.com/theupdateframework/tuf", "impact": {"cvss2_score": 4.9, "cvss2_severity": "MEDIUM", "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:N", "av": "NETWORK", "ac": "HIGH", "pr": "LOW", "c": "HIGH", "i": "HIGH", "a": "NONE", "impact_score": 5.8, "exploitability_score": 1.8, "cvss3_score": 8.2, "cvss3_severity": "HIGH", "ui": "NONE", "s": "CHANGED"}, "ochrona_severity_score": 8.2}